class Response:
    def __init__(self) -> None: ...
    @property
    def status(self) -> str: ...
    @status.setter
    def status(self, status: str) -> None: ...
    @property
    def media(self) -> object: ...
    @media.setter
    def media(self, media: object) -> None: ...